### ISSUE TITLE
Travis and Gh-pages needed for the repo

### ISSUE THREAD

**Issue by ypriverol** [ypriverol/CompProt2019-paper#11]
Anyone with experience in python notebooks that can help to configure the repo to serve https://github.com/ypriverol/CompProt2019-paper/blob/master/source/transform_poll.ipynb as python notebooks using travis. 

ping @bittremieux

**Comment by bittremieux** [comment]
What exactly do you want to do? If you just want to make an exploratory analysis of the data available the notebook will work just fine. I'm not sure what Travis has to do with that?

**Comment by ypriverol** [comment]
I would like to have a way that the current Jupyter note get publish in the repo (gh-pages for example) for other users. In the future, if you do a PR and I accept that PR, I would like to update the report automatically. The report would be for non-developer users. 

Is that possible?

**Comment by ypriverol** [comment]
I found the way. Now results can be checked here. https://ypriverol.github.io/CompProt2019-paper/ I'm now working in the notebook !!!!
