### ISSUE TITLE
repository name

### ISSUE THREAD

**Issue by lgatto** [ypriverol/CompProt2019-paper#8]
Not sure if `compomics` is an appropriate name for this repository, given this is also Lennarts's group name.

**Comment by ypriverol** [comment]
@lgatto we can change but a lot of people starred already the repo. and I can find a shorted name for `computational proteomics trends, challenges 2019` ;)

**Comment by lgatto** [comment]
Still not a good fit and confusing. And by the way, github manager repository renaming quite well.

**Comment by ypriverol** [comment]
@lgatto I can change it. What do you think about computational-proteomics-paper?

**Comment by lgatto** [comment]
What about `CompProtTrends2019`?

**Comment by ypriverol** [comment]
Do you like this CompProt2019-paper?

**Comment by lgatto** [comment]
:+1:

**Comment by ypriverol** [comment]
The repo has been renamed to CompProt2019-paper
